name: Run Cypress

on:
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Environment Variables
        run: |
          echo "CYPRESS_BASEURL=${{ secrets.BASEURL }}"
          echo "CYPRESS_APIBASEURL=${{ secrets.APIBASEURL }}"
          echo "CYPRESS_MAILSLURP_API_KEY=${{ secrets.MAILSLURP_API_KEY }}"

      - name: Create .env File
        run: |
          echo "CYPRESS_BASEURL=${{ secrets.BASEURL }}" > .env
          echo "CYPRESS_APIBASEURL=${{ secrets.APIBASEURL }}" >> .env
          echo "CYPRESS_MAILSLURP_API_KEY=${{ secrets.MAILSLURP_API_KEY }}" >> .env

      - name: Install Dependencies
        run: npm install

      - name: Cypress Execution
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_MAILSLURP_API_KEY: ${{ secrets.MAILSLURP_API_KEY }}
          CYPRESS_BASEURL: ${{ secrets.BASEURL }}
          CYPRESS_APIBASEURL: ${{ secrets.APIBASEURL }}
