name: Run Cypress

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create .env file
      run: echo "CYPRESS_BASEURL=${{ secrets.BASEURL }}" > .env
      # run: echo "CYPRESS_MAILSLURP_API_KEY=${{secrets.MAILSLURP_API_KEY}}" > .env
      # run: echo "CYPRESS_APIBASEURL-${{secrets.APIBASEURL}}" > .env

    - name: Show URL
    run: console.log('Environment Variables:', process.env);
      
    - name: Cypress Execution
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_MAILSLURP_API_KEY: ${{secrets.MAILSLURP_API_KEY}}
        CYPRESS_BASEURL: 'https://staging.trymima.com'
        CYPRESS_APIBASEURL: 'https://reqres.in'
