name: Run Cypress

on:
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Environment Variables
        run: |
          echo "CYPRESS_BASEURL='https://staging.trymima.com'"
          echo "CYPRESS_APIBASEURL='https://reqres.in'"
          echo "CYPRESS_MAILSLURP_API_KEY=${{ secrets.MAILSLURP_API_KEY }}"

      - name: Create .env File
        run: |
          echo "CYPRESS_BASEURL='https://staging.trymima.com'" > .env
          echo "CYPRESS_APIBASEURL='https://reqres.in'" >> .env
          echo "CYPRESS_MAILSLURP_API_KEY=${{ secrets.MAILSLURP_API_KEY }}" >> .env

      - name: Install Dependencies
        run: npm install

      - name: Cypress Execution
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
        env:
          CYPRESS_MAILSLURP_API_KEY: ${{ secrets.MAILSLURP_API_KEY }}
          CYPRESS_BASEURL: "https://staging.trymima.com"
          CYPRESS_APIBASEURL: "https://reqres.in"
