name: Run Cypress

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cypress Execution
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_MAILSLURP_API_KEY: ${{secrets.MAILSLURP_API_KEY}}
        CYPRESS_BASEURL: ${{secrets.BASEURL}}
        CYPRESS_APIBASEURL: ${{secrets.APIBASEURL}}
